# Generated by Django 5.1 on 2024-09-12 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiprovider',
            old_name='api_key',
            new_name='api_keys',
        ),
    ]
