# we'll keep the version for now to work in Compose and Swarm

services:
  db:
    image: postgres
    environment:
       POSTGRES_USER: ${DB_USER:-postgres} 
       POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres} 
    volumes:
      - ~/Postgress/data:/var/lib/postgresql/data
      - "./healthchecks:/healthchecks"
      # - ./db:/docker-entrypoint-initdb.d/
    ports:
      - "5432:${DB_PORT:-5432}"
    healthcheck:
      test: /healthchecks/postgres.sh
      interval: "5s"
  server:
    build: 
      context: ./server
      dockerfile: ./Dockerfile
    container_name: usedtube_backend
    command: sh -c "python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    restart: always
    environment:
       ENV_MODE: production 
       DB_USER: ${DB_USER} 
       DB_PASSWORD: ${DB_PASSWORD}
       DB_HOST: ${DB_HOST}
       DB_PORT: ${DB_PORT:-5432}
    ports:
      - "9090:8000"
      - "8001:8001"
#    volumes:
#          - "./gunicorn:/app/gunicorn"
    depends_on:
        db:
          condition: service_healthy
