# Generated by Django 4.1.13 on 2024-08-30 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '__first__'),
        ('sharing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareditem',
            name='file_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='files.file'),
        ),
    ]
