# Generated by Django 4.1.13 on 2024-08-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='compressed_size',
            field=models.IntegerField(default=0),
        ),
    ]
