# Generated by Django 4.1.13 on 2024-08-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('files', '0002_file_compressed_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='compressed_size',
            field=models.IntegerField(),
        ),
    ]
