# Generated by Django 4.1.13 on 2024-08-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('files', '0003_alter_file_compressed_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='compressed_size',
            field=models.IntegerField(null=True),
        ),
    ]
