import unittest

from engine.serialization.test_serializer import SerializerTest


codec_list = [
    # "alias_pix",
    # "amv",
    # "apng",
    # "asv1",
    # "asv2",
    "av1",
    # "av1_amf",
    # "av1_nvenc",
    # "av1_qsv",
    # "av1_vaapi",
    # "avrp",
    # "avs2",
    # "avui",
    # "bitpacked",
    # "bmp",
    # "cfhd",
    # "cinepak",
    # "cljr",
    # "dirac",
    # "dnxhd",
    # "dpx",
    # "dvvideo",
    # "dxv",
    # "exr",
    # "ffv1",
    # "ffvhuff",
    # "fits",
    # "flashsv",
    # "flashsv2",
    # "flv1",
    # "gif",
    # "h261",
    # "h263",
    # "h263p",
    "h264",
    # "h264_amf",
    "h264_mf",
    # "h264_nvenc",
    # "h264_qsv",
    # "h264_vaapi",
    # "hdr",
    "hevc",
    # "hevc_amf",
    # "hevc_mf",
    # "hevc_nvenc",
    # "hevc_qsv",
    # "hevc_vaapi",
    # "huffyuv",
    "jpeg2000",
    # "jpegls",
    # "jpegxl",
    # "libaom-av1",
    # "libjxl",
    # "libkvazaar",
    # "openh264",
    # "librav1e",
    # "libsvtav1",
    # "theora",
    # "libvpx",
    # "libwebp",
    # "libwebp_anim",
    "libopenjpeg",
    "libvpx-vp9",
    "libx264",
    "x264rgb",
    "libx265",
    "libxavs2",
    "xvid",
    "mpeg1video",
    "mpeg2_vaapi",
    "mpeg2video",
    "mpeg4",
    "vp9",
    # "magicyuv",
    # "mjpeg",
    # "mjpeg_qsv",
    # "mjpeg_vaapi",
    # "mpeg2_qsv",
    # "msmpeg4",
    # "msmpeg4v2",
    # "msmpeg4v3",
    # "msrle",
    # "msvideo1",
    # "pam",
    # "pbm",
    # "pcx",
    # "pfm",
    # "pgm",
    # "pgmyuv",
    # "phm",
    # "png",
    # "ppm",
    # "prores",
    # "prores_aw",
    # "prores_ks",
    # "qoi",
    # "qtrle",
    # "r10k",
    # "r210",
    # "rawvideo",
    # "roq",
    # "roqvideo",
    # "rpza",
    # "rv10",
    # "rv20",
    # "sgi",
    # "smc",
    # "snow",
    # "speedhq",
    # "sunrast",
    # "svq1",
    # "targa",
    # "theora",
    # "tiff",
    # "utvideo",
    # "v210",
    # "v308",
    # "v408",
    # "v410",
    # "vbn",
    # "vc2",
    # "vnull",
    # "vp8",
    # "vp8_vaapi",
    # "vp9_qsv",
    # "vp9_vaapi",
    # "wbmp",
    # "webp",
    # "wmv1",
    # "wmv2",
    # "wrapped_avframe",
    # "xbm",
    # "xface",
    # "xwd",
    # "y41p",
    # "yuv4",
    # "zlib",
    # "zmbv"
]
# codec_list = [
# # 'dirac',
# 'mpegvideo',
# 'libvpx-vp9',
# 'vc1',
# 'jpeg2000',
# 'h264',
# 'vp9',
# 'tscc2',
# 'mpeg1video',
# 'mpeg2video',
# 'hevc',
# 'png',
# 'libdav1d',
# 'mjpeg',
# 'mpeg4',
# 'vp9'
#     ]


# Test class for running tests for each codec
for codec_pair in codec_list:
    codec = codec_pair
    file_ext = "mp4"
    test_method_name_Bit_Block = 'test_serializer_pdf_1B_1Block_{0}_{1}'.format(codec, file_ext)


    # Function to perform the test for a specific codec

    def test_bit_block(self, codec_arg=codec, file_ext_arg=file_ext):
        SerializerTest.perform_test_1Bit_Block(self, codec_arg, file_ext_arg)


    setattr(SerializerTest, test_method_name_Bit_Block, test_bit_block)
    # break
if __name__ == '__main__':
    unittest.main()
